export const TYPES = {
  Application: Symbol.for('Application'),
  Logger: Symbol.for('Logger'),
  UsersController: Symbol.for('UsersController'),
  TagsController: Symbol.for('TagsController'),
  UsersService: Symbol.for('UsersService'),
  TagsService: Symbol.for('TagsService'),
  ConfigService: Symbol.for('ConfigService'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
  RepositoryService: Symbol.for('RepositoryService'),
  UsersRepository: Symbol.for('UsersRepository'),
  TagsRepository: Symbol.for('TagsRepository'),
  JwtService: Symbol.for('JwtService'),
  DbConfig: Symbol.for('DbConfig'),
};
